### ISSUE TITLE
crash when passing in a png as input to avifenc

### ISSUE THREAD

**Issue by darix** [AOMediaCodec/libavif#31]
```
#0  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:50
#1  0x00007feb30f5155d in __GI_abort () at abort.c:79
#2  0x00007feb30fab45f in __libc_message (action=action@entry=do_abort, fmt=fmt@entry=0x7feb310b9f49 "%s\n") at ../sysdeps/posix/libc_fatal.c:181
#3  0x00007feb30fb28fc in malloc_printerr (str=str@entry=0x7feb310bbb80 "free(): double free detected in tcache 2") at malloc.c:5332
#4  0x00007feb30fb472d in _int_free (av=0x7feb310ec9e0 <main_arena>, p=0x555794e21290, have_lock=0) at malloc.c:4201
#5  0x00005557934da7a8 in main (argc=<optimized out>, argv=<optimized out>) at /usr/src/debug/libavif-0.5.2-1.1.x86_64/apps/avifenc.c:214
```

**Comment by joedrago** [comment]
Currently, avifenc only supports y4m as a valid input, but I'll do a bit better job protecting against malformed y4m files.

**Comment by joedrago** [comment]
https://github.com/AOMediaCodec/libavif/commit/70e16bb58da03f45117dd82c980c4a1a7908065c
